### ISSUE TITLE
Overachieving Makefile

### ISSUE THREAD

**Issue by rebeccagcoffman** [joel-coffman/latex-incubator#46]
`Makefile.tex` runs `pdflatex` numerous times for a single `make`. Is there a way to have a "quick and dirty" `make` rule that only runs once, thus eliminating the longer, and often unnecessary, wait?

**Comment by joel-coffman** [comment]
A minimum working example to reproduce this issue would be nice, but yes, `Makefile.tex` runs `pdflatex` in draft mode twice before attempting to produce a PDF (i.e., a total of three runs of `pdflatex`). The multiple runs essentially assume that all documents have some sort of cross-references that should be resolved.

It might make sense to have a `draft` phony target that compiles once without attempting to resolve any cross references (or handle references, glossaries, indexes, etc.). That is, one could execute `make draft` to compile a document. Would that be useful?

**Comment by joel-coffman** [comment]
### Minimal Working Example

`Makefile`:
~~~ makefile
mwe.pdf: mwe.tex
mwe.tex:
	cat > $@ <<< '\documentclass{article}\begin{document}\end{document}'

include $(shell git rev-parse --show-toplevel)/texmf/Makefile.tex
~~~

Executing `make` (technically `make --dry-run`):
~~~ shell
rm -f mwe.sta
TEXINPUTS=.::../texmf//: pdflatex -shell-escape -draftmode mwe.tex
if grep -E '^\\@istfilename' mwe.aux; then makeglossaries -d . mwe && TEXINPUTS=.::../texmf//: pdflatex -shell-escape -draftmode mwe.tex; fi
files=$(sed -n 's/\\@input{\(.*\)}/\1/p' mwe.aux); if grep --quiet -E '\\(citation)' mwe.aux $files; then BIBINPUTS=.::../texmf//: bibtex mwe; fi
TEXINPUTS=.::../texmf//: pdflatex -shell-escape -draftmode mwe.tex
if [ -f mwe.idx ]; then makeindex $(if [[ mwe.tex == *.dtx ]]; then echo -s gind.ist; fi) -o mwe.ind mwe.idx; fi
if [ -f mwe.glo ]; then makeindex -s $(if [[ mwe.tex == *.dtx ]]; then echo gglo; else echo mwe; fi).ist -o mwe.gls mwe.glo; fi
TEXINPUTS=.::../texmf//: pdflatex -shell-escape mwe.tex
while ( grep -q '^LaTeX Warning: Label(s) may have changed' mwe.log ) do TEXINPUTS=.::../texmf//: pdflatex -shell-escape mwe.tex; done
~~~
Using `-draftmode` prevents `pdflatex` from producing an output PDF. Using draft mode doesn't do much else (see [pdflatex -draftmode much slower compared to draft option passed to graphicx](https://tex.stackexchange.com/a/129748) and [What is the correct way to use draft mode with arara?](https://tex.stackexchange.com/a/350895)) and could be omitted, but the later invocations of `pdflatex` would need to be conditional, using [various heuristics to determine if additional runs are needed](https://tex.stackexchange.com/a/265746).
